name: 'Analyse Issue Comment'
description: 'Analyses an issue comment to see if it contains an instruction.'
author: 'Karl Hulme'
inputs:
  authorisedLogins:
    description: 'A comma-separated list of logins that are authorised to trigger actions from issue comments.'
    required: true
  comment:
    description: 'The comment object raised with the event.'
    required: true
outputs:
  instruction:
    description: 'A value of ''release'' or empty.'
  releaseBranch:
    description: 'If the instruction is ''release'' this value will contain the name of the branch to be released.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'