name: 'Analyse Issue Comment'
description: 'Analyses an issue comment to see if it contains an instruction.'
author: 'Karl Hulme'
inputs:
  authorisedLoginsCsv:
    description: 'A comma-separated list of logins that are authorised to invoke instructions via issue comments.'
    required: true
  commentJson:
    description: 'The comment object raised with the event expressed as a JSON string.'
    required: true
outputs:
  instruction:
    description: 'A value of ''release'' or empty.'
  analysisFailureReason:
    description: 'If the analysis was not successful then this value will contain the reason.'
  branchName:
    description: 'If the instruction is ''release'' or ''publish'' this value will contain the name of the branch to be actioned.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'